### ISSUE TITLE
App list empty

### ISSUE THREAD

**Issue by mlaps** [vackosar/search-based-launcher#51]
I've been using search based launcher for about a year as an app drawer replacement on my Note 2.  I just got a Note 4 and installed SBL from F-Droid v59 and the application list to be empty.  I've restarted a couple of times and also waited for a bit in case it needed some time to populate the list, but still nothing.  Previously I was rooted and running Cyanogenmod 12.1, but this should work on devices that don't have root, right?  Any idea what might be going on?

Also, just an FYI.  I tried to donate a few dollars via PayPal and got a notification that it could not go through at this time.

**Comment by jruere** [comment]
Try clearing the cache of the app, that fixes it for me.

This has begun happening to me too after switching to an S7.

**Comment by mlaps** [comment]
Thanks for the suggestion, but clearing cache did not fix the issue.  I've also tried completely uninstalling and reinstalling.  No change.  The menu items all work perfectly, and the screen for the application list is there, the keyboard pops up, etc...  Just no items in the list (and typing the name of an application also does not do anything).

**Comment by jruere** [comment]
It must be something else then. A re-install also should fix the problem I
see.

**Comment by mlaps** [comment]
I did not dwell on this, as it was always my attention to root and install a rom, and I was hoping that when I did that the issue would go away.  However I just installed a new Marshmallow ROM yesterday, and still no luck with the launcher.  I noticed that another app I use, Hangar, that bases ordering depending on the amount of time spent in the app required the explicit granting of permissions now to access that data.  Something I don't recall on either the KitKat or Lollipop ROMs I was previously on.  Is there maybe a new permission setting in Marshmallow?  Or else is this a TouchWiz issue?  I'd previously been using the launcher on CyanogenMod 12.1,

**Comment by jruere** [comment]
It does work most of the time so it does not look as a permission issue.

**Comment by mlaps** [comment]
For me I can't get it to work at all on this phone.  App list is always empty.  Hopefully next week I will have time to try and install an AOSP based rom and see if I can get the app list to populate.

**Comment by mlaps** [comment]
Flashed Lineage 14.1 today and installed Search Based Launcher first thing and everything is working normally,  So my best guess is there is some TouchWiz compatibility issue (or at least TW as implemented on the Note 4).  But I'm just happy to have my text launcher back.
